---
# - name: loop over all ec2 regins
#   ansible.builtin.include_tasks:
#     file: retrieve_info.yml
#   loop: "{{ ec2_regions }}"

# - name: do the thing
#   shell: "ls -la /usr/libexec | grep platform-python"
#   register: output 

# - name: print the thing 
#   debug:
#     msg: "{{ output }}"
# - name: Get facts for current logged in user
#   azure.azcollection.azure_rm_account_info:
#   register: azure_account_info

# - name: print azure_account_info
#   ansible.builtin.debug:
#     msg: "{{ azure_account_info }}"
- name: Get list of all regions
  azure.azcollection.azure_rm_resource_info:
    url: "/locations"
    api_version: "2020-01-01"
  register: result

- name: print #var
  debug:
    msg: "{{ result }}"

- name: get all networks
  azure.azcollection.azure_rm_virtualnetwork_info:
  register: azure_networks

- name: print azure_networks
  ansible.builtin.debug:
    msg: "{{ azure_networks }}"

- name: get all vms
  azure.azcollection.azure_rm_virtualmachine_info:
  register: azure_vms

- name: print azure_vms
  ansible.builtin.debug:
    msg: "{{ azure_vms }}"