---
# - name: loop over all ec2 regins
#   ansible.builtin.include_tasks:
#     file: retrieve_info.yml
#   loop: "{{ ec2_regions }}"

# - name: do the thing
#   shell: "ls -la /usr/libexec | grep platform-python"
#   register: output 

# - name: print the thing 
#   debug:
#     msg: "{{ output }}"
- name: Get facts for current logged in user
  azure.azcollection.azure_rm_account_info:
  register: azure_account_info

- name: print azure_account_info
  ansible.builtin.debug:
    msg: "{{ azure_account_info }}"

- name: get all networks
  azure.azcollection.azure_rm_virtualnetwork_info:
  register: azure_networks

- name: print azure_account_info azure_networks
  ansible.builtin.debug:
    msg: "{{ azure_networks }}"

- name: List automation account in a resource group
  azure.azcollection.azure_rm_automationaccount_info:
  register: automationaccount_info

- name: print automationaccount_info
  ansible.builtin.debug:
    msg: "{{ automationaccount_info }}"

# - name: grab boto version
#   ansible.builtin.pip:
#     name: boto3
#   register: register_boto3_version
#   check_mode: true

# - name: grab information about AWS user
#   amazon.aws.aws_caller_info:
#   register: whoami
#   delegate_to: localhost

# - name: save username of AWS user and boto3 version
#   set_fact:
#     aws_user: '{{ whoami.arn.split("/")[-1] }}'
#     boto3_version: >-
#       {{ lookup('pipe', ansible_playbook_python ~ ' -c "import boto3; print(boto3.__version__)"') | default('unknown') }}    
#   delegate_to: localhost