---
- name: Check Services
  ansible.builtin.service_facts:
  register: service_facts

- name: Check if /etc/motd file exists
  ansible.builtin.stat:
    path: /etc/motd
  register: motd_file

- name: Check if selinux is enabled
  ansible.builtin.command: getenforce
  register: selinux_status
