---
- name: loop over all ec2 regins
  ansible.builtin.include_tasks:
    file: retrieve_info.yml
  loop: "{{ ec2_regions }}"

- name: grab boto version
  ansible.builtin.pip:
    name: boto3
  register: register_boto3_version
  check_mode: true

- set_fact:
    boto3_version: '{{ boto3[7:] }}'
  vars:
    boto3: '{{ register_boto3_version.stdout_lines | select("match","boto3") | first }}'

- name: grab information about AWS user
  amazon.aws.aws_caller_info:
    region: "{{ ec2_region }}"
  register: whoami
  delegate_to: localhost

- name: print whoami
  debug:
    var: whoami
  delegate_to: localhost

- name: save username of AWS user
  set_fact:
    aws_user: '{{ whoami.arn.split("/")[-1] }}'
    py_cmd: >-
      {{ lookup('pipe', ansible_playbook_python ~ ' -c "import boto3; print(boto3.__version__)"') }}
  delegate_to: localhost