---
- hosts: ssm
  tasks:
    - name: do something
      command: ls -la
      register: output

    - name: print out output
      debug:
        var: output

    - name: do something
      vars:
        ansible_connection: "community.aws.aws_ssm"
        ansible_aws_ssm_region: "us-east-1"
        ansible_aws_ssm_bucket_name: "ssmtestingoctober"
        ansible_aws_ssm_instance_id: i-09793f817c1a29bf4
        ansible_user: ssm-user
      ansible.builtin.file:
        path: blah.txt
        state: touch
      register: output

    - name: print out output
      debug:
        var: output
