---
- name: build report with facts
  hosts: ansible-1
  gather_facts: true
  vars:
    ec2_region: us-east-1

  tasks:
    - name: load retrieve info role
      include_role:
        name: "../roles/retrieve_info"
      loop: ["us-east-1","us-east-2"]

    - name: build a report
      include_role:
        name: "../roles/build_report"
