---
- hosts: localhost
  become: yes
  vars:
    report_server: node1
  
  tasks:
  - include_role:
      name: "../collections/ansible_collections/roles/patch_linux"

  - block:

    - include_role:
        name: "{{ item }}"
      loop:
        - "../collections/ansible_collections/roles/report_server"
        - "../collections/ansible_collections/roles/report_linux"
        - "../collections/ansible_collections/roles/report_linux_patching"

    - include_role:
        name: "../collections/ansible_collections/roles/report_server"
        tasks_from: linux_landing_page
        
    delegate_to: "{{ report_server }}"
    run_once: yes
