---
- hosts: "{{ HOSTS }}"
  become: yes
  vars:
    report_server: rhel1
  
  tasks:
  - include_role:
      name: patch_linux

  - block:

    - include_role:
        name: "{{ item }}"
      loop:
        - report_server
        - report_linux
        - report_linux_patching

    - include_role:
        name: report_server
        tasks_from: linux_landing_page
        
    delegate_to: "{{ report_server }}"
    run_once: yes
